const ANIMATED_COUNT_FIRST_DESCRIPTION = "App Downloads";
const ANIMATED_COUNT_SECOND_DESCRIPTION = "Happy Clients";
const ANIMATED_COUNT_THIRD_DESCRIPTION = "Active User";
const ANIMATED_COUNT_FOURTH_DESCRIPTION = "Active User";

const ANIMATED_COUNT_LABELS = {
  ANIMATED_COUNT_FIRST_DESCRIPTION,
  ANIMATED_COUNT_SECOND_DESCRIPTION,
  ANIMATED_COUNT_THIRD_DESCRIPTION,
  ANIMATED_COUNT_FOURTH_DESCRIPTION,
};

export { ANIMATED_COUNT_LABELS };
